# Generated by Django 4.2.6 on 2023-11-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loop2leap_Web', '0002_user_soft_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
